version: "3"
services:
  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile.dev
    image: hot-mapping-vis-server
    restart: unless-stopped
    ports:
      - "8080:80"
    links:
      - api:api
      - frontend:frontend

  frontend:
    build:
      context: ../.
      dockerfile: docker/frontend/Dockerfile.dev
    image: hot-mapping-vis-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./../frontend:/app
    ports:
      - "3000:3000"

  renderer:
    build:
      context: ../.
      dockerfile: docker/renderer/Dockerfile.dev
    image: hot-mapping-vis-renderer
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./../renderer:/app
      - ./capture:/capture

  api:
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile.dev
    image: hot-mapping-vis-api
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./../api:/app
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
    ports:
      - "4000:4000"

  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "15672:15672"
      - "5672:5672"
