version: "3"

services:
  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile.dev
    image: hot-mapping-vis-server
    restart: always
    ports:
      - "8080:80"
    links:
      - api
      - frontend

  frontend:
    build:
      context: ../.
      dockerfile: docker/frontend/Dockerfile.dev
    image: hot-mapping-vis-frontend
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./../frontend:/app
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
    links:
      - api
    ports:
      - "3000:3000"

  renderer:
    build:
      context: ../.
      dockerfile: docker/renderer/Dockerfile.dev
    image: hot-mapping-vis-renderer
    restart: always
    environment:
      - NODE_ENV=development
      - RENDER_QUEUE=render_queue
    links:
      - rabbitmq
    volumes:
      - ./../renderer:/app
      - ./data/capture:/data/capture
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones

  api:
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile.dev
    image: hot-mapping-vis-api
    restart: always
    environment:
      - NODE_ENV=development
      - RENDER_QUEUE=render_queue
    volumes:
      - ./../api:/app
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
    links:
      - db
      - rabbitmq
    ports:
      - "4000:4000"

  db:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "15672:15672"
      - "5672:5672"
