version: "3"

services:
  server:
    build:
      context: ../.
      dockerfile: docker/server/Dockerfile
    image: hot-mapping-vis-server
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./data/capture:/data/capture # volume shared with nginx
    depends_on:
      - api
      - frontend

  frontend:
    build:
      context: ../.
      dockerfile: docker/frontend/Dockerfile.dev
    image: hot-mapping-vis-frontend-dev
    restart: on-failure
    environment:
      - NODE_ENV=development
      - MAPBOX_ACCESS_TOKEN       # env passed from shell
      - MAP_VECTOR_SOURCE_MAXZOOM # env passed from shell
      - MAP_LAYER_MINZOOM         # env passed from shell
    volumes:
      - ./../frontend:/app
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
    ports:
      - "3000:3000"

  renderer:
    build:
      context: ../.
      dockerfile: docker/renderer/Dockerfile.dev
    image: hot-mapping-vis-renderer-dev
    restart: on-failure
    environment:
      - NODE_ENV=development
      - RENDER_QUEUE=render_queue
      - MAPBOX_ACCESS_TOKEN       # env passed from shell
      - MAP_VECTOR_SOURCE_MAXZOOM # env passed from shell
      - MAP_LAYER_MINZOOM         # env passed from shell
    depends_on:
      - rabbitmq
    volumes:
      - ./../renderer:/app
      - ./data/capture:/data/capture # volume shared with nginx
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones

  api:
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile.dev
    image: hot-mapping-vis-api-dev
    restart: on-failure
    environment:
      - NODE_ENV=development
      - RENDER_QUEUE=render_queue
      - MAILGUN_FROM=visualize@hotosmmail.org
      - MAILGUN_API_KEY # env passed from shell
      - MAILGUN_DOMAIN # env passed from shell
      - SERVER_DOMAIN # env passed from shell
      - POSTGRES_PASSWORD # env passed from shell
      - POSTGRES_USER # env passed from shell
    volumes:
      - ./../api:/app
      - ./data/tiles:/data/tiles
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
    depends_on:
      - db
      - rabbitmq
    ports:
      - "4000:4000"

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD # env passed from shell
      - POSTGRES_USER # env passed from shell
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./../db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3
    hostname: "rabbitmq"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

